version: "3"

services: 
  monolitico:
    build: ./monolitico
  user:
    build: ./microservicios/user
  chat:
    build: ./microservicios/chat
  nginx:
    image: nginx:latest
    ports:
      - "8080:8080"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - monolitico
      - user
      - chat